### ISSUE TITLE
version 1.1.0 not work on eclipse 2024-06

### ISSUE THREAD

**Issue by Danipiario** [nathantippy/eclipse-terra-arch#1]
Hi, I try to install plugin with version 1.1.0 but it fails with these error:
```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Can't download artifact osgi.bundle,net.TerraArch.editor,1.1.0 required by net.TerraArch.editor[1.1.0], net.TerraArch.editor[1.1.0], org.eclipse.osgi.services[3.12.100.v20240327-0645], net.TerraArch.feature.group[1.1.0], org.slf4j.api[1.7.30.v20200204-2150] from any of the following repositories: ...
```
I see a fork that pearhaps solve this problem but I don't know hot to install or compile the plugin.

**Comment by nathantippy** [comment]
I will look into this as soon as I can. I hope to have a solution early next week.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by kmf-lab** [comment]
I found time tonight to fix it for the new eclipse on Java 21.  updates from https://terraarch.net/update   should let you install 1.1.21

**Comment by Danipiario** [comment]
it works, thks
